<?php

return [
    'pianeti' => [
        [
            'nome' => 'Tatooine',
            'sistema' => 'Sistema Tatoo',
            'settore' => 'Settore Arkanis',
            'popolazione' => '200,000',
            'tipo' => 'Deserto',
        ],
        [
            'nome' => 'Alderaan',
            'sistema' => 'Sistema Alderaan',
            'settore' => 'Settore Alderaan',
            'popolazione' => '2 miliardi',
            'tipo' => 'Montagne, pianure',
        ],
        [
            'nome' => 'Corellia',
            'sistema' => 'Sistema Corelliano',
            'settore' => 'Settore Corelliano',
            'popolazione' => '3 miliardi',
            'tipo' => 'Cittadino, urbano',
        ],
        [
            'nome' => 'Stewjon',
            'sistema' => 'Sistema Stewjon',
            'settore' => 'Sconosciuto',
            'popolazione' => 'Sconosciuta',
            'tipo' => 'Sconosciuto',
        ],
        [
            'nome' => 'Dagobah',
            'sistema' => 'Sistema Dagobah',
            'settore' => 'Settore Sluis',
            'popolazione' => 'Disabitato',
            'tipo' => 'Paludoso, foresta',
        ],
        [
            'nome' => 'Naboo',
            'sistema' => 'Sistema Naboo',
            'settore' => 'Settore Chommell',
            'popolazione' => '4.5 miliardi',
            'tipo' => 'Pianure, colline, laghi',
        ],
        [
            'nome' => 'Chandrila',
            'sistema' => 'Sistema Chandrila',
            'settore' => 'Settore Bormea',
            'popolazione' => '1.2 miliardi',
            'tipo' => 'Montagne, foreste',
        ],
        [
            'nome' => 'Jakku',
            'sistema' => 'Sistema Jakku',
            'settore' => 'Settore Sconosciuto',
            'popolazione' => 'Un milione',
            'tipo' => 'Deserto',
        ],
        [
            'nome' => 'Yavin 4',
            'sistema' => 'Sistema Yavin',
            'settore' => 'Settore Gordian Reach',
            'popolazione' => 'Sconosciuta',
            'tipo' => 'Foresta tropicale',
        ],
        [
            'nome' => 'Kamino',
            'sistema' => 'Sistema Kamino',
            'settore' => 'Settore Wild Space',
            'popolazione' => '1 miliardo',
            'tipo' => 'Oceano',
        ],
        [
            'nome' => 'Haruun Kal',
            'sistema' => 'Sistema Haruun Kal',
            'settore' => 'Settore Al’har',
            'popolazione' => 'Sconosciuta',
            'tipo' => 'Giungla',
        ],
        [
            'nome' => 'Socorro',
            'sistema' => 'Sistema Kibilini',
            'settore' => 'Settore Kibilini',
            'popolazione' => 'Sconosciuta',
            'tipo' => 'Deserto, vulcanico',
        ],
        [
            'nome' => 'Serenno',
            'sistema' => 'Sistema Serenno',
            'settore' => 'Settore Sconosciuto',
            'popolazione' => 'Sconosciuta',
            'tipo' => 'Montagne, colline',
        ],
        [
            'nome' => 'Shili',
            'sistema' => 'Sistema Shili',
            'settore' => 'Settore Expansion Region',
            'popolazione' => 'Sconosciuta',
            'tipo' => 'Savane, foreste',
        ],
    ],
];
